### ISSUE TITLE
It doesn't find files in a vendor directory

### ISSUE THREAD

**Issue by jurgenhaas** [smakman/generator-gulp-bootstrap#2]
I've installed this successfully and ran gulp afterwards. What I'm getting is this error message then:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: File not found: /PATH/src/vendor/jquery/dist/jquery.js
  at include (/PATH/node_modules/gulp-include/index.js:107:13)
  at wrappedMapper (/PATH/node_modules/gulp-include/node_modules/event-stream/node_modules/map-stream/index.js:84:19)
  at Stream.stream.write (/PATH/node_modules/gulp-include/node_modules/event-stream/node_modules/map-stream/index.js:96:21)
  at write (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:104:17)
  at emitReadable_ (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:104:17)
  at emitReadable_ (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /PATH/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at evalmachine.<anonymous>:334:14
  at /PATH/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:102:5
  at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
```

What could I do about this?

**Comment by smakman** [comment]
Did you run bower install?

**Comment by jurgenhaas** [comment]
Sorry, no. I missed that. Maybe that should go into the "Getting started" section on your project's README.

Now gulp is running but it show the following error lines:

```
/PATH/src/js/app.js: line 17, col 5, Missing "use strict" statement.
/PATH/src/js/app.js: line 17, col 36, Strings must use singlequote.
/PATH/src/js/app.js: line 17, col 74, Strings must use singlequote.
/PATH/src/js/app.js: line 29, col 80, Strings must use singlequote.
/PATH/src/js/app.js: line 38, col 32, Strings must use singlequote.
/PATH/src/js/app.js: line 46, col 1, Missing "use strict" statement.
/PATH/src/js/app.js: line 70, col 22, Strings must use singlequote.
/PATH/src/js/app.js: line 99, col 17, Strings must use singlequote.
/PATH/src/js/app.js: line 111, col 22, Expected '!==' and instead saw '!='.
/PATH/src/js/app.js: line 185, col 37, Strings must use singlequote.
/PATH/src/js/app.js: line 194, col 36, Strings must use singlequote.
/PATH/src/js/app.js: line 206, col 43, Expected '!==' and instead saw '!='.
/PATH/src/js/app.js: line 244, col 22, Strings must use singlequote.
/PATH/src/js/app.js: line 244, col 71, Strings must use singlequote.
/PATH/src/js/app.js: line 256, col 47, Strings must use singlequote.
/PATH/src/js/app.js: line 262, col 22, Expected '!==' and instead saw '!='.
/PATH/src/js/app.js: line 278, col 45, Strings must use singlequote.
/PATH/src/js/app.js: line 283, col 73, Strings must use singlequote.
/PATH/src/js/app.js: line 301, col 20, Expected '===' and instead saw '=='.
/PATH/src/js/app.js: line 302, col 28, Strings must use singlequote.
/PATH/src/js/app.js: line 305, col 39, Strings must use singlequote.
/PATH/src/js/app.js: line 305, col 68, Strings must use singlequote.
/PATH/src/js/app.js: line 306, col 57, Strings must use singlequote.
/PATH/src/js/app.js: line 321, col 43, Strings must use singlequote.
/PATH/src/js/app.js: line 322, col 57, Strings must use singlequote.
/PATH/src/js/app.js: line 337, col 48, Strings must use singlequote.
/PATH/src/js/app.js: line 396, col 23, Expected '===' and instead saw '=='.
/PATH/src/js/app.js: line 397, col 15, Strings must use singlequote.
/PATH/src/js/app.js: line 398, col 24, Strings must use singlequote.
/PATH/src/js/app.js: line 398, col 45, Strings must use singlequote.
/PATH/src/js/app.js: line 405, col 20, Expected '!==' and instead saw '!='.
/PATH/src/js/app.js: line 408, col 44, Strings must use singlequote.
/PATH/src/js/app.js: line 420, col 22, Expected '===' and instead saw '=='.
/PATH/src/js/app.js: line 469, col 30, Expected '!==' and instead saw '!='.
/PATH/src/js/app.js: line 479, col 30, Expected '!==' and instead saw '!='.
/PATH/src/js/app.js: line 497, col 41, Strings must use singlequote.
/PATH/src/js/app.js: line 529, col 76, Strings must use singlequote.
/PATH/src/js/app.js: line 529, col 86, Strings must use singlequote.
/PATH/src/js/app.js: line 530, col 27, Strings must use singlequote.
/PATH/src/js/app.js: line 530, col 40, Strings must use singlequote.
/PATH/src/js/app.js: line 539, col 26, Strings must use singlequote.
/PATH/src/js/app.js: line 542, col 29, Strings must use singlequote.
/PATH/src/js/app.js: line 550, col 28, Strings must use singlequote.
/PATH/src/js/app.js: line 551, col 35, Strings must use singlequote.
/PATH/src/js/app.js: line 589, col 23, Strings must use singlequote.
/PATH/src/js/app.js: line 604, col 22, Unexpected use of '<<'.
/PATH/src/js/app.js: line 610, col 0, Identifier 'push_native' is not in camel case.
/PATH/src/js/app.js: line 626, col 140, Strings must use singlequote.
/PATH/src/js/app.js: line 631, col 39, Strings must use singlequote.
/PATH/src/js/app.js: line 633, col 59, Strings must use singlequote.
/PATH/src/js/app.js: line 633, col 59, Too many errors. (5% scanned).
```

What's strange though, the app.js file only contains 3 commented lines and not those lines that are referenced in the messages.

**Comment by smakman** [comment]
If you use the yeoman generator it runs bower install automatically. The lines in app.js are includes and the messages you are seeing are JSLint warnings. Those should not prevent the app from running.

**Comment by jurgenhaas** [comment]
Interesting. Bower wasn't available on my new Linux box and yeoman obviously ignored that silently. Maybe bower should be included in the dependencies?

**Comment by jurgenhaas** [comment]
Did some more testing today and all is working just fine now. I'm very impressed and I like it a lot. Thank you for your great work.

Now, I'm wondering how to move that forward. My own use case is development of Bootstrap subthemes for the Drupal CMS. The file structure and some of the setup is different. Does it make sense to make your package customizable or would you recommend a fork?

**Comment by smakman** [comment]
I've created this yeoman generator for our own projects, so the file structure and setup is very opinionated. I would recommend creating a fork for your own setup or even your own generator.

**Comment by jurgenhaas** [comment]
OK, thanks a lot. If you don't mind, what's required to create my own generator then?

**Comment by smakman** [comment]
You have to create a node module, check out the [Yeoman documentation](http://yeoman.io/authoring/). Also have a look at my [package.json](https://github.com/smakman/generator-gulp-bootstrap/blob/master/package.json) and [index.js](https://github.com/smakman/generator-gulp-bootstrap/blob/master/app/index.js) to get you started.
